[env]

[alias]
dv = "run --manifest-path dv/Cargo.toml --bin rust-dv --"
pre-commit = "run --manifest-path dv/Cargo.toml --bin pre_commit --"

[build]
rustflags = ['--cfg', 'feature="nonzero_internals"']