name: Verify VOSTD Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-24.04
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y build-essential unzip pkg-config libssl-dev llvm

      - name: Run xtask bootstrap
        run: cargo xtask bootstrap

      - name: Run verification
        run: |
          make 2>&1 | tee verus.log
          if grep -q "error:" verus.log; then
            echo "Verification errors found"
            exit 1
          fi